//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.2012
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Kernys.Bson;
using UnityEngine;

namespace TcpBsonClient
{
	public interface IClientCmd
	{

		void decode(BSONObject obj);
	}
}

